# Source: https://mwolson.org/blog/2025-11-12-ghostty-tmux-uniform-copy-paste/

copy-on-select = false
keybind = performable:ctrl+shift+c=copy_to_clipboard
# remap super+c to ctrl+shift+c, use `bash -i -c cat` to see keycodes
# as you type them
keybind = super+c=csi:99;6u
selection-invert-fg-bg = true
shell-integration-features = no-cursor
