# Source: https://mwolson.org/blog/2025-11-12-ghostty-tmux-uniform-copy-paste/
# Made a compromise on using Command-Shift-C because remapping Command-C to Ctrl-Shift-C in normal
# circumstances (e.g. running an app locally on mac) behaves poorly

copy-on-select = false
keybind = performable:ctrl+shift+c=copy_to_clipboard
# remap command-shift-c to ctrl-shift-c for tmux copy-mode
keybind = super+shift+c=csi:99;6u
selection-invert-fg-bg = true
shell-integration-features = no-cursor
