# Source: https://mwolson.org/blog/2025-11-12-ghostty-tmux-uniform-copy-paste/
# And https://dev.to/jsonarso/your-ghostty-keybindings-are-broken-heres-the-60-second-fix-4kio
# Made a compromise on using Command-Shift-C because remapping Command-C to Ctrl-Shift-C in normal
# circumstances (e.g. running an app locally on mac) behaves poorly

macos-option-as-alt = true
copy-on-select = false
keybind = performable:ctrl+shift+c=copy_to_clipboard
# remap command-shift-c to ctrl-shift-c for tmux copy-mode
keybind = super+shift+c=csi:99;6u
selection-invert-fg-bg = true
shell-integration-features = no-cursor

# Perhaps fix remote tmux'd claude code shift-enter w/tmux `extended-keys off`
keybind = shift+enter=text:\n
