cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'cloudflared'
brew 'imagemagick'
brew 'postgresql@14'
brew 'redis'
brew 'spaceman-diff'
brew 'spark'
brew 'wget'
brew 'yt-dlp'

cask 'azure-data-studio'
cask 'aldente'
cask 'android-platform-tools'
cask 'diffusionbee'
cask 'handbrake'
cask 'microsoft-edge'
cask 'orcaslicer'
cask 'plex'
cask 'raycast'
cask 'tailscale'
cask 'warp'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'zoom'
cask 'whatpulse/whatpulse/whatpulse'
cask 'todoist'
cask 'spotify'
cask 'syncthing'
